name: CI - Artemis Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'packages/artemis/**'

permissions:
  deployments: write
  contents: read
  packages: write

jobs:
  artemis-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build and Deploy Artemis Docker Image
        uses: ./.github/actions/docker-build
        with:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          DOCKERFILE: artemis.Dockerfile
          IMAGE_NAME: artemis
          DOKPLOY_API_URL: ${{ secrets.DOKPLOY_API_URL }}
          DOKPLOY_API_KEY: ${{ secrets.DOKPLOY_API_KEY }}
          DOKPLOY_COMPOSE_ID: ${{ secrets.ARTEMIS_DOKPLOY_COMPOSE_ID }}
